/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicletracker;

import com.google.gson.Gson;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.http.HttpResponse;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.CredentialsProvider;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.util.EntityUtils;

/**
 *
 * @author gemorgan
 */
public class ManageVehicleForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageVehicleForm
     */
    public ManageVehicleForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnViewVehicleCat = new javax.swing.JButton();
        btnAddCar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Make", "Model", "Year", "Number Plate", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("View Vehicles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Limos", "Trailer", "Buses" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnViewVehicleCat.setText("View Vehicle by Category");
        btnViewVehicleCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVehicleCatActionPerformed(evt);
            }
        });

        btnAddCar.setText("Add Car");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddCar)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)
                        .addGap(55, 55, 55)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewVehicleCat))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewVehicleCat)
                    .addComponent(btnAddCar)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        CredentialsProvider provider = new BasicCredentialsProvider();
        UsernamePasswordCredentials credentials
         = new UsernamePasswordCredentials("root", "root");
        provider.setCredentials(AuthScope.ANY, credentials);
        
        
        try
        {
        HttpClient client = HttpClientBuilder.create()
                 .setDefaultCredentialsProvider(provider)
                .build();
        HttpGet request = new HttpGet("http://localhost:8080/car/readAllCars"); 
        HttpResponse response = client.execute(request);
        
        
        String json = EntityUtils.toString(response.getEntity());
        Gson gson = new Gson();// TODO add your handling code here:
        Car[] cars = gson.fromJson(json, Car[].class);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        for(Car thing : cars) {

            Object[] rowData = new Object[]{
                thing.getMake(),
                thing.getModel(),
                thing.getYear(),
                thing.getNumberPlate(),
                thing.getStatus()
            };
            model.addRow(rowData);
        }
        
        }
   
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnViewVehicleCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVehicleCatActionPerformed
        // TODO add your handling code here:
            CredentialsProvider provider = new BasicCredentialsProvider();
        UsernamePasswordCredentials credentials
         = new UsernamePasswordCredentials("root", "root");
        provider.setCredentials(AuthScope.ANY, credentials);
        
        
        try
        {
        HttpClient client = HttpClientBuilder.create()
                 .setDefaultCredentialsProvider(provider)
                .build();
        HttpGet request = new HttpGet("http://localhost:8080/car/readAllCars"); 
        HttpResponse response = client.execute(request);
        
        
        String json = EntityUtils.toString(response.getEntity());
        Gson gson = new Gson();// TODO add your handling code here:
        Car[] cars = gson.fromJson(json, Car[].class);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        for(Car thing : cars) {
            Object[] rowData = new Object[]{
                thing.getMake(),
                thing.getModel(),
                thing.getYear(),
                thing.getNumberPlate(),
                thing.getStatus(),
                thing.getCategoryId()
            };
            if(jComboBox1.getSelectedItem() == "Sedan")
            {
                if(thing.getCategoryId() == 1 )
                {
                     model.addRow(rowData);
                }
            }
            
             if(jComboBox1.getSelectedItem() == "SUV")
            {
                if(thing.getCategoryId() == 2 )
                {
                     model.addRow(rowData);
                }
            }
             
              if(jComboBox1.getSelectedItem() == "Limos")
            {
                if(thing.getCategoryId() == 3 )
                {
                     model.addRow(rowData);
                }
            }
              
               if(jComboBox1.getSelectedItem() == "Trailer")
            {
                if(thing.getCategoryId() == 4 )
                {
                     model.addRow(rowData);
                }
            }
               
                if(jComboBox1.getSelectedItem() == "Buses")
            {
                if(thing.getCategoryId() == 5 )
                {
                     model.addRow(rowData);
                }
            }
           
        }
        
        }
   
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnViewVehicleCatActionPerformed

    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        // TODO add your handling code here:
        
      this.setVisible(false);
      NewCarForm form = new NewCarForm();
      form.setVisible(true);
           
      
    }//GEN-LAST:event_btnAddCarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        AdminForm form = new AdminForm();
        form.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageVehicleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnViewVehicleCat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
