/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicletracker;

import com.google.gson.Gson;
import javax.swing.table.DefaultTableModel;
import org.apache.http.HttpResponse;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.CredentialsProvider;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.util.EntityUtils;

/**
 *
 * @author gemorgan
 */
public class ManageRentalForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageRentalForm
     */
    public ManageRentalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnViewRentals = new javax.swing.JButton();
        lblTotalAmount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnOutRental = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Amount", "Rent Date", "Return Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnViewRentals.setText("View All Rentals");
        btnViewRentals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRentalsActionPerformed(evt);
            }
        });

        lblTotalAmount.setText("0.00");

        jLabel1.setText("Total Amount");

        btnOutRental.setText("View Outstanding Rentals");
        btnOutRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutRentalActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addComponent(btnOutRental)
                        .addGap(80, 80, 80)
                        .addComponent(btnViewRentals)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalAmount)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnViewRentals)
                        .addComponent(btnOutRental)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotalAmount)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRentalsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        
         CredentialsProvider provider = new BasicCredentialsProvider();
        UsernamePasswordCredentials credentials
         = new UsernamePasswordCredentials("root", "root");
        provider.setCredentials(AuthScope.ANY, credentials);
        
        double totalAmount = 0;
        
        try
        {
        HttpClient client = HttpClientBuilder.create()
                 .setDefaultCredentialsProvider(provider)
                .build();
        HttpGet request = new HttpGet("http://localhost:8080/rent/findAllRentedCars"); 
        HttpResponse response = client.execute(request);
        
        
        String json = EntityUtils.toString(response.getEntity());
        System.out.println(json);
        Gson gson = new Gson();// TODO add your handling code here:
        Rent[] rents = gson.fromJson(json, Rent[].class);
        
        
        
        for(Rent thing : rents) {
            
            Object[] rowData = new Object[]{
                thing.getID(),
                thing.getTotalPrice(),
                thing.getRentDate(),
                thing.getReturnDate()
            };
           totalAmount = totalAmount + thing.getTotalPrice().doubleValue();
            model.addRow(rowData);
           }
        lblTotalAmount.setText(String.valueOf(totalAmount));
        }
        catch(Exception e)
                {
                
                }
    }//GEN-LAST:event_btnViewRentalsActionPerformed

    private void btnOutRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutRentalActionPerformed
        // TODO add your handling code here:
        
        CredentialsProvider provider = new BasicCredentialsProvider();
        UsernamePasswordCredentials credentials
         = new UsernamePasswordCredentials("root", "root");
        provider.setCredentials(AuthScope.ANY, credentials);
        
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
        model.setRowCount(0);
        
        double totalAmount = 0;
        
        try
        {
        HttpClient client = HttpClientBuilder.create()
                 .setDefaultCredentialsProvider(provider)
                .build();
        HttpGet request = new HttpGet("http://localhost:8080/rent/findAllRentedCars"); 
        HttpResponse response = client.execute(request);
        
        
        String json = EntityUtils.toString(response.getEntity());
        System.out.println(json);
        Gson gson = new Gson();// TODO add your handling code here:
        Rent[] rents = gson.fromJson(json, Rent[].class);
        
 
        
        for(Rent thing : rents) {
            
            Object[] rowData = new Object[]{
                thing.getID(),
                thing.getTotalPrice(),
                thing.getRentDate(),
                thing.getReturnDate(),
            };
            if(thing.isOutstanding())
            {
           totalAmount = totalAmount + thing.getTotalPrice().doubleValue();
            model.addRow(rowData);
            }
           }
        lblTotalAmount.setText(String.valueOf(totalAmount));
        }
        catch(Exception e)
                {
                
                }
    }//GEN-LAST:event_btnOutRentalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        AdminForm form = new AdminForm();
        form.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRentalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOutRental;
    private javax.swing.JButton btnViewRentals;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTotalAmount;
    // End of variables declaration//GEN-END:variables
}
